services:
  mauricioferreira-blog:
    build: .
    ports:
      - "1313:1313"
    volumes:
      - ./content:/app/content
      - ./static:/app/static
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./hugo.yaml:/app/hugo.yaml
    environment:
      - HUGO_ENV=development
    command: >
      sh -c "
        cd /app &&
        hugo server --logLevel debug --disableFastRender -p 1313 --bind 0.0.0.0 --watch
      "
    restart: unless-stopped